### PR TITLE
Updating to Zelus 2.2

### LINKED ISSUE #9: Migrate to Zélus 2.2
Looks like we need to fetch everything up to inria/zelus:2.2, which is up to commit 56febdf

### PR DESCRIPTION
**Pull request by nskh**
Rebased on top of [Zelus 2.2 commit](https://github.com/INRIA/zelus/commit/56febdfc91bb35eb5cf5c1aa6d04119b048d0a28)

I ran `git pull upstream 56febdfc91bb35eb5cf5c1aa6d04119b048d0a28 --rebase` and I had to fix one merge conflict in `compilers/dune` to get this to rebase cleanly

Closes #9.

### CODE REVIEW

**Comment by nskh** [comment]
@jlvargasme it looks like this branch has the conflicts fixed - is it also up to date with your latest changes to https://github.com/jeannin/zelus/tree/dependent_types? 

@jchen-cs this may be ready for review and testing, if so

**Comment by jlvargasme** [comment]
> @jlvargasme it looks like this branch has the conflicts fixed - is it also up to date with your latest changes to https://github.com/jeannin/zelus/tree/dependent_types?
> 
> @jchen-cs this may be ready for review and testing, if so

Yes, the latest changes from dependent_types are present in this request.

**Review by jchen-cs — APPROVED** [review]
Looking good! I'll approve the pull request

**Review by jlvargasme — APPROVED** [review]
The latest changes are present here. Approving

**Review by jchen-cs — COMMENTED** [review]
I ran some tests on my local machine, but it looks like there's some issues with the dependencies in `compiler/dune`. I managed to get compilation to pass by removing `compiler simulator fixstep` from line 17, but not sure if anything else depends on it. @jlvargasme Does making that change affect any of the parts you've worked on?

**Review by jchen-cs — CHANGES_REQUESTED** [review]
Changed to "request changes" to reflect the dependency issue during testing

**Review by jchen-cs — APPROVED** [review]

**Review by jlvargasme — APPROVED** [review]
Unit tests passed

**Pull request merged**
